# Site settings
title: S A U C E
header-img: img/home-bg.jpg
email: helena.tiongson@gmail.com
description: "Oh hey."
baseurl: ""
url: "http://helmt.github.io"
twitter_username: he1ena
github_username:  helmt
facebook_username:  helena.tiongson

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
